pipeline {

    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
              dir 'angular-shooping-cart'
              sh 'npm install'
            }
        }
        stage('Run') {
            steps {
                echo 'Running...'
              dir 'angular-shooping-cart'
                bat 'npm start'
            }
        }
    }
}
