pipeline {

    agent any
    tools {nodejs "node"}
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                bat 'npm install'
            }
        }
    }
}
